import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import User from 'App/Models/User'

export default class UserSeeder extends BaseSeeder {
  public async run() {
    await User.createMany([
      {
        role_id : 1,
        dept_id : 1,
        name : 'Superadmin',
        email : 'superadmin@test.tes',
        nik : 'AJC001',
        password : '123456',
        avatar : 'testing.png',
        work_location : 'office',
        saldo_cuti : 12,
        activation : 'true',
        hp : '081212439564',
        status : 'tetap',
        tgl_join : new Date(),
        limit_kasbon : 2000000,
        total_gaji_perbulan : 2000000,
      },
      {
        role_id: 2,
        dept_id: 6,
        name: 'Direktur Utama',
        email: 'dirut@test.tes',
        nik: 'AJC002',
        password: '123456',
        avatar: 'testing.png',
        work_location: 'office',
        saldo_cuti: 12,
        activation: 'true',
        hp: '081212439564',
        status: 'tetap',
        tgl_join: new Date(),
        limit_kasbon: 2000000,
        total_gaji_perbulan: 2000000,
      },
      {
        role_id: 3,
        dept_id: 2,
        name: 'Direktur Finance',
        email: 'dir_finance@test.tes',
        nik: 'AJC003',
        password: '123456',
        avatar: 'testing.png',
        work_location: 'office',
        saldo_cuti: 12,
        activation: 'true',
        hp: '081212439564',
        status: 'tetap',
        tgl_join: new Date(),
        limit_kasbon: 2000000,
        total_gaji_perbulan: 2000000,
      },
      {
        role_id: 4,
        dept_id: 1,
        name: 'Direktur Operasional',
        email: 'dir_operasional@test.tes',
        nik: 'AJC004',
        password: '123456',
        avatar: 'testing.png',
        work_location: 'office',
        saldo_cuti: 12,
        activation: 'true',
        hp: '081212439564',
        status: 'tetap',
        tgl_join: new Date(),
        limit_kasbon: 2000000,
        total_gaji_perbulan: 2000000,
      },
      {
        role_id: 5,
        dept_id: 2,
        name: 'Staff Finance',
        email: 'staff_finance@test.tes',
        nik: 'AJC005',
        password: '123456',
        avatar: 'testing.png',
        work_location: 'office',
        saldo_cuti: 12,
        activation: 'true',
        hp: '081212439564',
        status: 'tetap',
        tgl_join: new Date(),
        limit_kasbon: 2000000,
        total_gaji_perbulan: 2000000,
      },
      {
        role_id: 6,
        dept_id: 3,
        name: 'Staff Gudang',
        email: 'staff_gudang@test.tes',
        nik: 'AJC006',
        password: '123456',
        avatar: 'testing.png',
        work_location: 'gudang',
        saldo_cuti: 12,
        activation: 'true',
        hp: '081212439564',
        status: 'tetap',
        tgl_join: new Date(),
        limit_kasbon: 2000000,
        total_gaji_perbulan: 2000000,
      },
      {
        role_id: 7,
        dept_id: 3,
        name: 'Kepala Gudang',
        email: 'kepala_gudang@test.tes',
        nik: 'AJC007',
        password: '123456',
        avatar: 'testing.png',
        work_location: 'gudang',
        saldo_cuti: 12,
        activation: 'true',
        hp: '081212439564',
        status: 'tetap',
        tgl_join: new Date(),
        limit_kasbon: 2000000,
        total_gaji_perbulan: 2000000,
      },
      {
        role_id: 8,
        dept_id: 3,
        name: 'Wakil Kepala Gudang',
        email: 'wakep_gudang@test.tes',
        nik: 'AJC008',
        password: '123456',
        avatar: 'testing.png',
        work_location: 'gudang',
        saldo_cuti: 12,
        activation: 'true',
        hp: '081212439564',
        status: 'tetap',
        tgl_join: new Date(),
        limit_kasbon: 2000000,
        total_gaji_perbulan: 2000000,
      },
      {
        role_id: 9,
        dept_id: 3,
        name: 'Logistik Gudang',
        email: 'logistik_gudang@test.tes',
        nik: 'AJC009',
        password: '123456',
        avatar: 'testing.png',
        work_location: 'gudang',
        saldo_cuti: 12,
        activation: 'true',
        hp: '081212439564',
        status: 'tetap',
        tgl_join: new Date(),
        limit_kasbon: 2000000,
        total_gaji_perbulan: 2000000,
      },
      {
        role_id: 10,
        dept_id: 3,
        name: 'Helper Gudang',
        email: 'helper_gudang@test.tes',
        nik: 'AJC010',
        password: '123456',
        avatar: 'testing.png',
        work_location: 'gudang',
        saldo_cuti: 12,
        activation: 'true',
        hp: '081212439564',
        status: 'tetap',
        tgl_join: new Date(),
        limit_kasbon: 2000000,
        total_gaji_perbulan: 2000000,
      },
      {
        role_id: 11,
        dept_id: 3,
        name: 'Kurir Gudang',
        email: 'kurir_gudang@test.tes',
        nik: 'AJC011',
        password: '123456',
        avatar: 'testing.png',
        work_location: 'gudang',
        saldo_cuti: 12,
        activation: 'true',
        hp: '081212439564',
        status: 'tetap',
        tgl_join: new Date(),
        limit_kasbon: 2000000,
        total_gaji_perbulan: 2000000,
      },
      {
        role_id: 12,
        dept_id: 3,
        name: 'Kepala Toko',
        email: 'kep_toko@test.tes',
        nik: 'AJC012',
        password: '123456',
        avatar: 'testing.png',
        work_location: 'toko',
        saldo_cuti: 12,
        activation: 'true',
        hp: '081212439564',
        status: 'tetap',
        tgl_join: new Date(),
        limit_kasbon: 2000000,
        total_gaji_perbulan: 2000000,
      },
      {
        role_id: 13,
        dept_id: 3,
        name: 'Wakil Kepala Toko',
        email: 'wakep_toko@test.tes',
        nik: 'AJC013',
        password: '123456',
        avatar: 'testing.png',
        work_location: 'toko',
        saldo_cuti: 12,
        activation: 'true',
        hp: '081212439564',
        status: 'tetap',
        tgl_join: new Date(),
        limit_kasbon: 2000000,
        total_gaji_perbulan: 2000000,
      },
      {
        role_id: 14,
        dept_id: 3,
        name: 'Kasir Toko',
        email: 'kasir_toko@test.tes',
        nik: 'AJC014',
        password: '123456',
        avatar: 'testing.png',
        work_location: 'toko',
        saldo_cuti: 12,
        activation: 'true',
        hp: '081212439564',
        status: 'tetap',
        tgl_join: new Date(),
        limit_kasbon: 2000000,
        total_gaji_perbulan: 2000000,
      },
      {
        role_id: 15,
        dept_id: 3,
        name: 'Sales Toko',
        email: 'sales_toko@test.tes',
        nik: 'AJC015',
        password: '123456',
        avatar: 'testing.png',
        work_location: 'toko',
        saldo_cuti: 12,
        activation: 'true',
        hp: '081212439564',
        status: 'tetap',
        tgl_join: new Date(),
        limit_kasbon: 2000000,
        total_gaji_perbulan: 2000000,
      }
    ])
  }
}
